hl7-debatch/README.md

change to readme for PR merge.

readme debatch

---

phin-vocab/.gitignore
phin-vocab/README.md
phin-vocab/host.json
phin-vocab/pom.xml
phin-vocab/src/main/java/cdc/gov/phinvads/vocab/HttpTriggerFunction.kt
phin-vocab/src/main/java/cdc/gov/phinvads/vocab/VocabClient.kt

Can you pls pull this branch into Main. thanks.

Phinvads vocab

---

docs/develop-environment/README.md
fns-hl7-pipeline/fn-receiver-debatcher/README.md

Mscaldas2012 patch 1

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/RedisProxy.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/StringUtils.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/StringUtilsTest.kt
local_libs/lib-dex-commons/src/test/kotlin/test/gov/cdc/dex/MetadataTest.kt

Created Redis Proxy 
Created String normalization functions

lib-dex-commons-1.0.1-SNAPSHOT

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/JsonHelper.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/UnknownPropertyError.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/JsonHelperTest.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/StringUtilsTest.kt
local_libs/lib-dex-commons/src/test/kotlin/test/gov/cdc/dex/MetadataTest.kt

method to read json properties

lib-dex-common 1.0.1-SNAPSHO

---

fns-hl7-pipeline/fn-message-processor/src/main/kotlin/gov/cdc/dex/hl7/MmgUtil.kt
fns-hl7-pipeline/fn-message-processor/src/main/kotlin/gov/cdc/dex/hl7/model/ConditionCode.kt

Mmg special cases logic

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/DexEventPayload.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/Provenance.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/DateHelper.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/StringUtils.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/DateHelperTest.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/StringUtilsTest.kt
local_libs/lib-dex-commons/src/test/kotlin/test/gov/cdc/dex/MetadataTest.kt
local_libs/lib-dex-commons/src/test/resources/KY_Hepatitis Round 2_TM1.txt

Added eventId and eventTimestamp to provenance.
added toIsoSttring for OffsetDateTime
Fixed metadata_version json prop name
added hashMD5 to create Hash Tables.

lib enhancements.

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/RedisProxy.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/mmg/MmgUtil.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/mmg/MmgUtilTest.kt

Closing redis connection upon finalize() - garbage collection

closing redis connections on gc

---

mrr/src/main/kotlin/gov/cdc/dex/mrr/EventCodeClient.kt
mrr/src/main/resources/groups/groups.csv
mrr/src/test/kotlin/gov/cdc/dex/mrr/EventCodeClientTest.kt

This function loads group: keys and associated sets into Redis cache.

add function loadGroups to EventCodeClient

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/JsonHelper.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/JsonHelperTest.kt
local_libs/lib-dex-commons/src/test/resources/mockEventHubPayload.json

making sure Gson serialize nulls

---

fns-hl7-pipeline/fn-structure-validator/pom.xml

updating validator function to use latest Lib NIST libraries

Nist upgrade

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/mmg/MmgUtil.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/mmg/MmgUtilTest.kt

adding back check of GenV2 MSH-21 to library

fixing msh21 check

---

fns-hl7-pipeline/fn-mmg-validator/pom.xml

the last merge somehow missed some changes on the POM.. 
I've fixed those and adding a PR again.

cleaning pom after merge

---

fns-hl7-pipeline/fn-structure-validator/pom.xml
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt
fns-hl7-pipeline/fn-structure-validator/src/main/resources/application.conf
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/gov/cdc/dex/ValidationTest.kt
fns-hl7-pipeline/fn-structure-validator/src/test/resources/Lyme_V1.0.2_TM_TC01.hl7
fns-hl7-pipeline/fn-structure-validator/src/test/resources/Lyme_WithWarnings.txt
fns-hl7-pipeline/fn-structure-validator/src/test/resources/Lyme_WithWarnings3.txt

Struct val pom

---

fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt

Update validator HttpTrigger function to catch exceptions and send appropriate http responses.

update validator function

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/StringUtils.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/mmg/MmgUtilTest.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/util/StringUtilsTest.kt

#474 
New Library version created - therefore, need to upgrade services using it

normalizing dots on strings

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/DexMessageInfo.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/mmg/MmgUtil.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/redisModels/Condition2MMGMapping.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/JsonHelper.kt
local_libs/lib-dex-commons/src/test/kotlin/gov/cdc/dex/mmg/MmgUtilTest.kt
local_libs/lib-dex-commons/src/test/kotlin/test/gov/cdc/dex/MetadataTest.kt

#558 - Added type as additional field in DexMessageInfo

#558 - Added type as an attribute to DexMessageInfo capture the type(ECR,ELR...) of message being processed.

---

fns-hl7-pipeline/fn-structure-validator/src/main/resources/application.conf

downgrade from ERROR to WARNING for x-usage, w-usage, cardinality

change application.conf for NIST validator 

---

mrr/src/main/kotlin/gov/cdc/dex/mrr/EventCodeClient.kt
mrr/src/main/kotlin/gov/cdc/dex/mrr/MmgatClient.kt

Update EventCodeClient and MmgatClient to use plain namespaces 

---

fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/MmgSqlTransProcessMetadata.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/TransformerSql.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/test/kotlin/MmgSqlTest.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/test/resources/Varicella_AZ_2021_1.txt

update mmg-sql transformer to support legacy MMGs with no epi OBR

---

svc-cloud-transport/pom.xml
svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/Application.kt
svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/TransportController.kt
svc-cloud-transport/src/main/resources/application.yml

-> changed package to gov.cdc.dex.cloud
-> upgrade dependencies

#601 - Implement svc-cloud-transport

---

svc-cloud-transport/pom.xml

Added profile to get the application deployed to Azure

Implement svc-cloud-transport. #601

---

fns-hl7-pipeline/fn-mmg-based-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Transformer.kt
fns-hl7-pipeline/fn-mmg-based-transformer/src/test/kotlin/MbtTest.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/TransformerSql.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/test/resources/mmgBasedModel1.json
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/StringUtils.kt
mrr/src/main/resources/event_codes/ncird_events.csv

Uses lib-dex-commons 1.0.11 with getNormalizedShortName function to produce/read truncated names in JSON model for repeating elements and repeating groups.

MMG-Based and MMG-SQL transformer update

---

fns-hl7-pipeline/fn-mmg-validator/pom.xml
fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/DateUtil.kt
fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/MmgValidator.kt
fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/model/ValidationIssue.kt
fns-hl7-pipeline/fn-mmg-validator/src/test/kotlin/MMGValidatorTest.kt
fns-hl7-pipeline/fn-mmg-validator/src/test/resources/Lyme_BadDate.txt

Update MMG Validator with DateUtil date validation class

---

fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Helper.kt
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/model/RedactorProcessMetadata.kt
fns-hl7-pipeline/fn-redactor/src/test/kotlin/FunctionTest.kt
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt

#623 - Added config names to Metadata

#623 - Added config names to Metadata

---

fns-hl7-pipeline/fn-structure-validator/pom.xml
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/model/StructureValidatorProcessMetadata.kt
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/gov/cdc/dex/EventHubPayloadTest.kt
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/gov/cdc/dex/ValidationTest.kt

#UIL9_623_Structure_validator - Changes to populate config

#UIL9_623_Structure_validator - Changes to populate config

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/receiver/Function.kt

Fix for null pointer exception

---

fns-hl7-pipeline/fn-mmg-validator/pom.xml
fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/MMGValidationFunction.kt
fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/model/MmgValidatorProcessMetadata.kt

#623 - Add config information in the Metadata

#623 - Add config information in the Metadata

---

fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/MMGValidationFunction.kt
fns-hl7-pipeline/fn-mmg-validator/src/main/kotlin/gov/cdc/dex/hl7/model/MmgValidatorProcessMetadata.kt

#731 - Add process object to Metadata in exception block

#731 - Add process object to Metadata in exception block

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

#721 - Updated Summary to REDACTED

#721 - Updated Summary to REDACTED

---

fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/TransformerSql.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/test/resources/modelMalaria.json

fix bug where repeating elements were creating inner lists in rg tables

---

tools/upload-messages-py/upload_messages.py

Update to upload_messages.py script

update generated name to include original file name

---

fns-hl7-pipeline/fn-structure-validator/src/main/resources/application.conf

remove 'testing with custom error message' message

Update to structure validator application.conf

---

mrr/src/main/resources/event_codes/cgh_events.csv
mrr/src/main/resources/event_codes/ncezid_events.csv

NNDSS published an update to the condition codes list and this PR maps the new conditions to the generic v.2.0 mmg. Also updates to some of the preferred names for conditions

add new generic conditions from nndss update

---

fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/resources/DefaultFieldsProfileX.json

Gson did not like that we removed "preferred", so put it back and set it to false

add preferred=false to Alternate Identifier

---

local_libs/lib-bumblebee/src/main/kotlin/gov/cdc/dex/TemplateTransformer.kt

minor code cleanup

---

fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/TransformerSql.kt
fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/resources/DefaultFieldsProfileX.json

Test results were missing because of how block elements were being filtered. This PR fixes the issue

Update Lab Template SQL Model

---

fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Transformer.kt

mmg-based function was unable to load BasicProfile.json due to error in path syntax

fix bug in path to BasicProfile.json resource

---

CHANGELOG.md

- Created method to convert HL7 message into JSON, based on HL7-PET profiles.
- Created AZ function to process hl7 messages into JSON model based on method above.
- Updated HL7 Usage in Gen v1 MMG to "R" for all fields whose Cardinality is [1..1]
- Removed ZLR segments from Covid19 ELR Nist Profiles
- Improving logging statements of Receiver/Debatcher
- Added Code coverage for Lake Of Segments
- Improved Redis Proxy to use Connection pooling
- Removed constraint for HD fields that requires a valid OID
- Changed Unescaped delimiter errors from Error to Warning
- Using Class level configuration for Fn to improve performance - read configuration only once on class lifecycle

Release 0.0.20

---

fns-hl7-pipeline/fn-mmg-based-transformer/pom.xml

- added maven-deploy-plugin
- added distributionManagement section

Artifact configuration for mmg-based-transformer

---

fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml

- enabled deployments with via service principals
- remove duplicate maven-surefire-plugin reference to ensure stability of the build
- removed pluginDependecies section

enabled deploys for lake segs transformer

---

.github/workflows/hl7-remote-cicd.yml
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-based-transformer/pom.xml
fns-hl7-pipeline/fn-redactor/pom.xml

- Address "ref not found" error in file detection routine occurring during push requests.  
- Reorganize workflow to improve separation between manual and auto trigger jobs. 
- Display Deploy Process Names in Action viewer for better transparency

Fix:File Change Detection

---

.github/workflows/hl7-remote-cicd.yml

only trigger job on push to develop

---

tools/upload-messages-py/upload_messages.py

bug fix -- variables were not being set properly

add logging and change to class structure #HL7-1081

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml

- added distributionmanagement block for deploying to imagehub
-
-
- TBD
-

CDC-813: adding config for json lake

---

fns-hl7-pipeline/fn-structure-validator/pom.xml

- added distributionmanagement block for pom.xml -> imagehub integration
-
-
- TBD
-

CDC-812: adding config for structure validator

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HL7JSONLakeProcessMetadata.kt

update summary status values; add env vars to pom so tests will run; ……enforce non-null environment variables in FunctionConfig

Update summary metadata in json-lake function #HL7-1096

---

fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

update summary status to function-specific status

Update summary status in mmg-based function #HL7-1097

---

fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

update summary to use function-specific status values

Update summary status in mmg-sql function #HL7-1098

---

.github/workflows/hl7-remote-cicd.yml
fn-cache-loader/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-based-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-sql-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-validator/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-structure-validator/pom.xml
svc-cloud-transport/pom.xml

Update triggers (manual and automated) to pass source branch and deploy target input data to remote CD workflow. Add PR trigger for unit test/ci flow

CDC-876Feat-Update triggers to include CD workflow inputs

---

.github/workflows/hl7-remote-cicd.yml

revert deploy test changes and PR ci/unit test trigger to enable merge of trigger data changes

revert deploy test changes

---

local_libs/lib-dex-commons/build.gradle.kts

Lib dex commons

---

local_libs/lib-cloud-proxy/src/main/kotlin/gov/cdc/dex/cloud/storage/azure/BlobProxy.kt
local_libs/lib-cloud-proxy/src/test/kotlin/gov/cdc/dex/cloud/messaging/TestStorageQueue.kt
local_libs/lib-cloud-proxy/src/test/kotlin/gov/cdc/dex/cloud/storage/CloudStorageProxyTest.kt
local_libs/lib-cloud-proxy/src/test/kotlin/gov/cdc/dex/cloud/storage/TestStreamRead.kt
local_libs/lib-cloud-proxy/src/test/resources/application.yml

disable TestStorageQueue and TestStreamRead tests, fix listFolder function to list only folders from blob storage

#HL7-2198 Update unit tests on lib-cloud-proxy

---

local_libs/lib-cloud-proxy/build.gradle

Updated the imagehub credentials

update made to the cloud proxy imagehub credentials

---

.github/workflows/hl7-remote-cicd.yml
fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-based-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-sql-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-validator/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-structure-validator/pom.xml
svc-cloud-transport/pom.xml

Revert test updates accidentally merged to main in prior commit

HL7-2300 - add commit trigger

---

svc-cloud-transport/pom.xml

Revert webapp plugin version update due to address 503 app error

HL7-2300 Revert webapp plugin version update due to address 503

---

svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/TransportController.kt

respond to Azure Always On ping with "hello"

add ping response to transport webapp #HL7-2303

---

local_libs/lib-dex-commons/build.gradle.kts

marcelo teams chat commentary - un-commenting environment block

---

.github/workflows/hl7-remote-cicd.yml
local_libs/lib-bumblebee/pom.xml
local_libs/lib-nist-validator/pom.xml

Update Trigger to include HL7 shared lib workflows

HL7-2265 Add local libs to remote trigger

---

.github/workflows/hl7-remote-cicd.yml
fn-cache-loader/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-based-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-sql-transformer/pom.xml
fns-hl7-pipeline/fn-mmg-validator/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-structure-validator/pom.xml

Add version and helper plugins supporting release process

HL7-2224 Add version and helper plugins supporting release process

---

local_libs/lib-cloud-proxy/src/test/kotlin/gov/cdc/dex/cloud/messaging/TestStorageQueue.kt
local_libs/lib-cloud-proxy/src/test/kotlin/gov/cdc/dex/cloud/storage/CloudStorageProxyTest.kt
local_libs/lib-cloud-proxy/src/test/kotlin/gov/cdc/dex/cloud/storage/TestStreamRead.kt

Commented out all tests where "Test" annotation had been removed.
All tests pass locally.

Lib cloud proxy fix

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/PathUtils.kt

add PathUtils class, bump snapshot to 1.0.17

lib-dex-commons update related to rec-deb changes #HL7-2340

---

fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/receiver/Function.kt

Had a placeholder in there that needed to be changed to call getMessageInfo private function

fix bug #HL7-2334

---

fns-hl7-pipeline/fn-structure-validator/buildNumber.properties
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/gov/cdc/dex/ValidatorFunction.kt
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/gov/cdc/dex/ValidatorFunctionTest.kt

Create new PR for cdc-1024 in order to remove the "refactor" file .

cdc-1024/structure-validator-tests

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml

update lib-dex-commons reference to 1.0.18 snapshot

Receiver-debatcher lib-dex reference bump

---

deprecated/fn-lake-segs-transformer/Function.kt
fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-structure-validator/pom.xml

Lake-Segments-transformer: deprecate elr

Hl7 2344 remove function tied to hl7 structure elr

---

deprecated/fn-hl7-json-lake/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/buildNumber.properties
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/kotlin/HL7JsonLakeFunctionTest.kt

hl7-json-transformer: deprecate elr

Hl7 2346 remove function tied to hl7 structure elr ok

---

.github/workflows/hl7-remote-cicd.yml

Revert back to prior version of action to attempt to address 503 deploy issues

HL7-2375-Reapply changes updone in prior PR

---

fns-hl7-pipeline/fn-lake-segs-transformer/buildNumber.properties
fns-hl7-pipeline/fn-structure-validator/buildNumber.properties
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt

Removed full message log
Added log for message id and event hub topic output ( error or ok )

initial logging changes

---

fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt

Removed "Single Message" and "Event Message Received"

removed single message and event hub message log

---

tools/upload-messages-py/upload_messages.py

add timestamp to log; add prompts for message type, route, jurisdiction

enhancements to File Uploader script

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/receiver/Function.kt

Create Dummy change to verify correct versions are being deployed through ci/cd

HL7-2396 Deploy versions test

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/Provenance.kt

update for source_metadata

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/DexEventPayload.kt

add 'id' to DexEventPayload for CosmosDB

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/kotlin/HL7JsonLakeFunctionTest.kt

update pom to Java 17, kotlin 1.9.0, azure bom, add logback version; ……remove 'CASE' from fn name and env vars

json-lake bug fix #HL7-2463

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml

update pom to include azure BOM, Java 17, kotlin 1.9.0, function version 0.0.27-snapshot

#HL7-2444 update Receiver-Debatcher to include Azure BOM

---

fns-hl7-pipeline/fn-redactor/pom.xml

update pom to include azure BOM, version 0.0.27-snapshot, Java 17, kotlin 1.9.0

#HL7-2445 implement azure BOM in Redactor pom

---

fns-hl7-pipeline/fn-structure-validator/pom.xml

update pom to fix maven failsafe plugin version, change function version implementation, uncomment auth element block, remove azevhub variable

Structure Validator POM updates

---

fns-hl7-pipeline/fn-receiver-debatcher/host.json
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/gov/cdc/dex/hl7/FunctionTest.kt

cosmos db updates
updates for event hubs/output bindings
removing eventHunSender

debatcher updates for cosmos db #HL7-2456

---

fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/kotlin/HL7JsonLakeFunctionTest.kt

tested with azure, creates hl7-json-lake container

#HL7-2459 implement output bindings for event hubs and cosmos db

---

fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

Introduced finally block to handle output bindings, reshuffled some code

#2470 update for finally

---

fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

catch unsupported route and emit friendly error message

#HL7-2483 Unsupported Route in Structure Validator

---

fns-hl7-pipeline/fn-structure-validator/pom.xml

#HL7-2491 fix typo

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-structure-validator/pom.xml

Added App Service Plan with standard naming convention to the POM files.

Hl7 2478 elastic service plan cicd support

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

PR for HTTPTrigger for HL7 Json Lake

HL7-2487 - Added HTTPTrigger for json lake function app

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
tools/local-run/utils/src/main/kotlin/local/Utils.kt

debatcher: 
- discovered a bug for batched messages, not outputting all to cosmos db container
- fixed version in pom to 28
local-run:
- updated utils\..\Utils.kt,  removed .json extension for files in hl7-event

eph0 debatcher fix

---

tools/update-constraints-py/update_constraints.py

add renaming profile files to uppercase

Update to update_constraints.py tool

---

spikes/hl7-cosmosdb-poc/.gitignore
spikes/hl7-cosmosdb-poc/README.md
spikes/hl7-cosmosdb-poc/host.json
spikes/hl7-cosmosdb-poc/pom.xml
spikes/hl7-cosmosdb-poc/src/main/kotlin/gov/cdc/dex/Function.kt

This is the precursor for querying and creating various reports from dex cosmosDB containers

#HL7-2474 Basic POC for output and input bindings for comosDB

---

svc-cloud-transport/pom.xml
svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/TransportController.kt
svc-cloud-transport/src/main/resources/application.yml

So that all our web apps work the same way :)
Also upgrade Java, Kotlin, and Micronaut and use latest lib-cloud-proxy

#HL7-2549 Transport /health and /heartbeat

---

local_libs/lib-cloud-proxy/build.gradle
local_libs/lib-cloud-proxy/gradle.properties

update to Java 17 and Kotlin 1.9.0, bump version to 0.0.30-snapshot

Update lib-cloud-proxy Java and Kotlin versions

---

fns-hl7-pipeline/fn-structure-validator/host.json
fns-hl7-pipeline/fn-structure-validator/pom.xml

add maxBatch and prefetch count to host.json at 64/128, bump version to 0.0.30-snapshot

Structure Validator host.json update

---

svc-hl7-replay/pom.xml

Added repository information to pom for artifact upload

set distmgmt for pom

---

svc-hl7-replay/pom.xml
svc-hl7-validation/pom.xml

Added dist element for distro to pom for validation api

Hl7 2530 validator pom update

---

fns-hl7-pipeline/fn-hl7-json-lake/host.json
fns-hl7-pipeline/fn-hl7-json-lake/pom.xml

change host.json to include max batch and prefetch, bump version to 0.0.30-snapshot

JSON Lake Transformer max batch and prefetch

---

tools/upload-messages-py/upload_messages.py

Change original file name to new file name
Rename log file every hour

Updates to upload script

---

svc-hl7-replay/README.md

Updated Replay API readme file and added current design diagram

Update README.md for Replay API

---

fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-lake-segs-transformer/src/test/kotlin/LakeSegsFunctionTest.kt

remove cosmos db output binding from fn-lake-segs-transformer

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-redactor/pom.xml

Added new elastic2 plan to .pom for the 4 functions utilizing it.

added elastic2 ASP to poms

---

svc-hl7-validation/openapi.properties
svc-hl7-validation/pom.xml
svc-hl7-validation/src/main/kotlin/gov/cdc/dex/validation/service/Application.kt
svc-hl7-validation/src/main/kotlin/gov/cdc/dex/validation/service/HealthVersionIndicator.java
svc-hl7-validation/src/main/kotlin/gov/cdc/dex/validation/service/ValidationController.kt
svc-hl7-validation/src/main/resources/application.yml

- Add version number to /health endpoint output
- Add documentation of /health endpoint to Swagger UI
- Add Introduction section to Swagger UI
- Add parameter descriptions to Validation function documentation

#HL7-2602 Validation API Health Endpoint and Swagger Updates

---

tools/upload-messages-py/upload_messages.py

add hour to log filename, add start and end times to log, only log error messages, fix covid-19 profile name

Update upload script

---

.github/workflows/hl7-remote-cicd.yml

Inserted environment as input on merge trigger and manual invocation.

added targetEnv to merge trigger

---

.github/workflows/hl7-remote-cicd.yml

Added target env to remote ci/cd trigger

added env to remote-trigger

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml

Testing JSON Lake Merge Trigger

testing json lake merge trigger

---

tools/fn-copy-files/README.md
tools/fn-copy-files/host.json
tools/fn-copy-files/pom.xml
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/BlobFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/CosmosFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/StorageCopyFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/StorageFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/util/BlobService.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/util/PathHelper.kt

Implement StorageFunction "file-copy" azure function.

HL7-2649 Create a FN to move Files from Container A to Container B

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml

Removing comment for JSON LAKE unit testing/publish - Build/Deploy

removed comment for testing

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/constants/Constants.kt

the purpose is to reuse the constants.

added constants.kt to lib-dex-commons

---

tools/fn-copy-files/README.md
tools/fn-copy-files/pom.xml
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/CosmosFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/FileCopyFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/StorageCopyFunction.kt
tools/fn-copy-files/src/main/kotlin/gov/cdc/dataexchange/util/BlobService.kt

configure connection string as a secret, cleanup, bugfix, added counting optional header

HL7-2649 configure connection string as a secret, cleanup, bugfix

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml

update event hub send name in pom

Recdeb pom update

---

fns-hl7-pipeline/fn-structure-validator/pom.xml

Structure Validator pom update

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml

Json-lake pom update

---

fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml

Lake-segments pom update

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt

update receiver-debatcher to use lib-dex-commons with new metadata in DexEventPayload

#HL7-2725 Receiver-Debatcher add upload metadata values to DexEventPayload

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml

fix auth, remove app settings from pom

Fix receiver debatcher pom 

---

fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/AzureBlobProxy.kt

remove createIfNotExists from init

storage-sink update

---

fns-sidecars/hl7-file-sink/host.json
fns-sidecars/hl7-file-sink/pom.xml
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/AzureBlobProxy.kt

fix init section of AzureBlobProxy to initialize BlobContainerClient

file-sink sidecar initialization fix

---

fns-sidecars/hl7-file-sink/pom.xml
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/Function.kt
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt

update file-sink to log missing environment variables
if destination id is missing, set to 'unknown'

File-Sink sidecar update logging, set default destination

---

tools/update-constraints-py/update_constraints.py

update to rename files with uppercase prefix and lowercase '.xml' ext…ension

Update to update_constraints.py script

---

fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

update error message when profile identifier not found

#HL7-2756 structure validator profile ID error message

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverEventReport.kt

Requires new environment variable "EventReportsHubName" = "hl7-recdeb-reports"

#HL7-2770 Create report for each file received in rec-deb

---

svc-cloud-transport/pom.xml
svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/TransportController.kt

add Bad Request response if missing message_type or route metadata

#HL7-2559 Add feedback for missing metadata to Transport Service app

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml

- Testing whether bumping maven azure function plugin to 1.30.0 does anything at all.

Updating Maven plugin to 1.30.0 for receiver debatcher

---

fns-hl7-pipeline/fn-receiver-debatcher/host.json
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverEventReport.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt
fns-sidecars/hl7-file-sink/pom.xml
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/Function.kt
fns-sidecars/hl7-file-sink/src/test/kotlin/StorageSinkTest.kt
fns-sidecars/hl7-file-sink/src/test/resources/test_message.json
local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/DexEventPayload.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/Provenance.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/RoutingMetadata.kt

Includes updates to receiver-debatcher, file-sink, and lib-dex-commons

#HL7-2796 Receiver-Debatcher Report metadata

---

fns-hl7-pipeline/fn-structure-validator/pom.xml

removed maven-deploy to see if maven stops trying to refresh all FN when deploying to staging

cleanup pom

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverEventReport.kt

add metadata.processes process_name, add schema_version, schema_name

#HL7-2807 add elements to Receiver-Debatcher report

---

fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

Added Health Endpoint

---

svc-hl7-validation/pom.xml
svc-hl7-validation/src/main/kotlin/gov/cdc/dex/validation/service/HealthVersionIndicator.java

update custom health endpoint to include Liveness annotation, 
remove unnecessary dependencies to reduce size of jar

Validation API update

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

Health check endpoint

---

fns-hl7-pipeline/fn-structure-validator/pom.xml
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-structure-validator/src/main/resources/profiles/profile_config.json
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/ValidationTest.kt

update problem reporting to include better messaging around missing route or profile name, and remove exception stack trace

#HL7-2801 Structure Validator Error Messaging Update

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/RedactorFunction.kt
fns-hl7-pipeline/fn-redactor/src/test/kotlin/RedactorFunctionTest.kt

Renamed Function name

---

.github/workflows/hl7-remote-cicd.yml

Commented out main branch CI/CD trigger.

commentedOutMain

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-redactor/src/test/kotlin/RedactorFunctionTest.kt

Renamed health endpoint

---

fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

HL7-2784 : Health Endpoint

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

Created separated file for health endpoint

Created separated file for health endpoint

---

fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

HL7-2645 : Health Check Endpoint

HL7-2645 : Health Check Endpoint

---

fns-sidecars/fn-sc-processapi-report/pom.xml
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/ReportFunction.kt

refactor processing api sidecar to use synchronous, dedicated service bus sender

#HL7-2838 Processapi sidecar dedicated sender

---

fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

HL7-2785 : Health Check

---

fns-sidecars/fn-sc-branch/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt

HL7-2789 : Health Check

---

fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt

HL7-2787 : Health Check

---

fns-sidecars/fn-sc-processapi-report/pom.xml
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/ReportFunction.kt

refactor Service Bus sender code; remove 'output' node from report

#HL7-2846 PS sidecar: refactor sender and remove 'output' node from report

---

fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/ReportFunction.kt

ProcessStatus sidecar: remove 'output' from the correct place in the json

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HL7JSONLakeProcessMetadata.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/kotlin/HL7TransformerTest.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/resources/bigmessage.txt

reduce json size by eliminating nulls and empty arrays, remove 'content' node from result

#HL7-2855 Reduce JSON size in JSON Lake Transformer

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/DexMetadata.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/StageMetadata.kt

add StageMetadata, change DexMetadata to use StageMetadata, bump version to 0.0.39-snapshot

#HL7-2863 Replace Processes with Stage in DexMetadata

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HL7JSONLakeProcessMetadata.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/kotlin/HL7TransformerTest.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/kotlin/MetadataTest.kt
fns-hl7-pipeline/fn-hl7-json-lake/src/test/resources/test.json

update json-lake transformer to use stage instead of processes array in metadata, add unit test

#HL7-2858 Json-Lake replace Processes with Stage in Metadata

---

fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/LakeSegsTransProcessMetadata.kt

update lake-seg transformer to use stage element

#HL7-2859 Replace Processes with Stage in Lake of Segments Transformer

---

fns-hl7-pipeline/fn-structure-validator/pom.xml
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/model/StructureValidatorProcessMetadata.kt
fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/EventHubPayloadTest.kt

update structure validator to use stage element

#HL7-2860 Replace Processes with Stage in Structure Validator

---

fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/model/RedactorProcessMetadata.kt
fns-hl7-pipeline/fn-redactor/src/test/kotlin/FunctionTest.kt

update redactor to use stage instead of processes

#HL7-2861 Replace Processes with Stage in Redactor

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverProcessMetadata.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/gov/cdc/dex/hl7/FunctionTest.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/BatchMessage.txt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/CASE_message.txt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/CovidELRWithBlanks.txt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/ELR_message.txt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/ERROR_message.txt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/InvalidMessage.txt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/resources/NoMetadataFIle.txt

update recdeb to use stage instead of processes, update unit tests

#HL7-2862 Replace Processes with Stage in Receiver-Debatcher

---

fns-sidecars/fn-sc-branch/pom.xml
fns-sidecars/fn-sc-branch/src/main/kotlin/gov/cdc/dataexchange/Function.kt

update branch sidecar to read from stage element

#HL7-2866 Change Branch Sidecar to read from Stage instead of Processes

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/DedicatedEventHubSender.kt

update DedicatedEventHubSender to return list of indices of messages that were too large to send to event hub

#HL7-2856 Improve DedicatedEventHubSender to bypass messages that are too large for EH

---

fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt

HL7-2790-health

---

fns-sidecars/fn-sc-cosmosdb-sink/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt

HL7-2788-healthcheck

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HL7JSONLakeProcessMetadata.kt

update JsonLakeProcessMetadata to inherit from EventHubStageMetadata, use lib-dex version 0.0.41

JSON-Lake: Fix metadata

---

fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HL7JSONLakeStageMetadata.kt

HL7-2867 : Version from pom.xml

HL7-2867 : Version from pom.xml

---

fns-sidecars/fn-sc-processapi-report/pom.xml
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/ReportFunction.kt
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/model/ProcessingStatusSchema.kt

add schema name and version to report; fix metadata bug

#HL7-2870 Unique schema name and version for each PS report

---

fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/LakeSegsTransStageMetadata.kt

HL7-2898-version-env

---

fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverStageMetadata.kt

HL7-2899-version-env

---

fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/model/StructureValidatorStageMetadata.kt

HL7-2901- Version from env variable

HL7-2901- Version from env variable

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/model/RedactorStageMetadata.kt

HL7-2900 : Version from env variable

HL7-2900 : Version from env variable

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ProcessInfo.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverEventReport.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverMessageStageMetadata.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/ReceiverStageMetadata.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

Make the recdeb report a part of Stage element and change up the metadata to look more like the other pipeline stage reports.

#HL7-2902 Improve Recdeb Report Schema

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/InvalidMessageException.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/ProfileConfiguration.kt

add ProfileConfiguration, InvalidMessageException to lib-dex-commons util to support profile loading in different functions; bump version to 0.0.43-snapshot

Lib-dex-commons: Support for Profile Loading

---

svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/TransportController.kt

Hl7-2895-remove-old-metadata

---

fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

HL7-2877 : Enhanced health check

HL7-2877 : Enhanced health check

---

fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt

refactor some redundancy, add new routing metadata to event report

Receiver-Debatcher: refactor

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/DedicatedEventHubSender.kt

Added eventhub health check in common-libs

Added eventhub health check in common-libs

---

fns-hl7-pipeline/fn-structure-validator/pom.xml
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

upon exception, summary status is VALIDATION_FAILURE and report is null

#HL7-2954 Structure Validator: exception status is VALIDATION_FAILURE

---

fns-sidecars/hl7-file-sink/pom.xml
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/Function.kt
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt

update saveBlobToContainer to catch netty exception

File-sink: update saveBlobToContainer to catch netty exception

---

fns-sidecars/fn-sc-branch/pom.xml

- Added distribution management for branch functions

Added distribution management configuration

---

fns-hl7-pipeline/fn-receiver-debatcher/host.json
fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt

This change has the queue resend the queue message if the function throws an exception trying to read the blob or metadata.

Receiver-Debatcher: retry upon exception 

---

fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

Add check of event hub to redactor health check

#HL7-2877 Redactor: enhance health check

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/health/DependencyChecker.kt

Add overload to check event hub that takes connection string, event hub name as parameters

#HL7-2877 Health check enhancement: add overload for event hub check

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt

update routing metadata to include sender_id, received_filename

#HL7-2896 Update receiver-debatcher routing metadata for aims-celr

---

fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/Function.kt

get date folders from dex_ingest_datetime, fix logging of folder path

#HL7-2992 #HL7-2988 File-sink ingest datetime and logging fix

---

fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
fns-hl7-pipeline/fn-receiver-debatcher/src/test/kotlin/DebatcherTest.kt
fns-sidecars/hl7-file-sink/pom.xml
fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/Function.kt
local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/RoutingMetadata.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/util/DateHelper.kt

also includes updates to lib-dex-commons and subsequent changes to file-sink

#HL7-2997 Update Receiver-Debatcher to handle dex_ingest_datetime

---

svc-cloud-transport/pom.xml
svc-cloud-transport/src/main/kotlin/gov/cdc/dex/transport/service/TransportController.kt

force values passed in via x-tp- headers to lowercase

transport svc: force blob metadata values to lowercase

---

fns-sidecars/fn-sc-processapi-report/Dockerfile
fns-sidecars/fn-sc-processapi-report/example.env

add Dockerfile and example.env

#HL7-3013 Dockerize hl7-processingstatus

---

.github/workflows/pull-request-merge-main.yml
tools/codeScan/gitDiffAnalysis.py

Updating paths for Fortify Scanning engine.

Update Fortify paths

---

local_libs/lib-dex-commons/build.gradle.kts
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/metadata/RoutingMetadata.kt

add version to routing metadata, bump gradle version

lib-dex-commons: add version to routing metadata

---

svc-hl7-replay/src/main/kotlin/gov/cdc/dex/replay/service/ReplayController.kt

Code was not compiling, Added necessary parameters so that code can at least compile.

fixing parameters of pais to match documentation

---

tools/countScripts/countFiles.sh

Updating routing folders to include data-stream-id

Countfiles

---

fns-hl7-pipeline/fn-receiver-debatcher/Dockerfile
fns-hl7-pipeline/fn-receiver-debatcher/example.env

#HL7-3022 Receiver-Debatcher: Modify Dockerfile

---

fns-hl7-pipeline/fn-redactor/pom.xml

update redactor pom to use lib-dex-commons 0.0.51-snapshot

#HL7-3078 Enhance Redactor health checks

---

fns-hl7-pipeline/fn-structure-validator/pom.xml
fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

add event hub check to structure validator health check

#HL7-3071 Enhance Structure Validator health checks

---

fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

add event hub checks to health check

#HL7-3072 Enhance Json-Lake-Transformer health checks

---

fns-hl7-pipeline/fn-lake-segs-transformer/deployZip.sh
fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

add event hub checks to health check

#HL7-3073 Enhance Lake of Segments Health Checks

---

fns-sidecars/fn-sc-branch/deployZip.sh
fns-sidecars/fn-sc-branch/pom.xml
fns-sidecars/fn-sc-branch/src/main/kotlin/gov/cdc/dataexchange/Function.kt
fns-sidecars/fn-sc-branch/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt
fns-sidecars/fn-sc-branch/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt
local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/health/DependencyChecker.kt

update branch sidecar health checks to check event hub status, 
change event hub checker to not retry connection

#HL7-3076 Enhance Branch Sidecar health checks

---

fns-sidecars/fn-sc-processapi-report/deployZip.sh
fns-sidecars/fn-sc-processapi-report/pom.xml
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt
fns-sidecars/fn-sc-processapi-report/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt

update prcoessing status sidecar health checks to check service bus and event hub

#HL7-3075 #HL7-3068 Enhance PS API Sidecar health checks

---

fns-hl7-pipeline/fn-redactor/deployZip.sh
fns-hl7-pipeline/fn-redactor/pom.xml
fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/HealthCheckFunction.kt

add check of source event hub to redactor

#HL7-3078 Enhance Redactor health checks -- include inbound event hub

---

local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/health/DependencyChecker.kt

add timeout of 10 seconds with no retry to service bus queue health check

#HL7-3068 Lib-dex-commons Dependency checker: add timeout to Service Bus check

---

fns-hl7-pipeline/fn-hl7-json-lake/Dockerfile
fns-hl7-pipeline/fn-lake-segs-transformer/Dockerfile
fns-hl7-pipeline/fn-receiver-debatcher/Dockerfile
fns-hl7-pipeline/fn-redactor/Dockerfile
fns-hl7-pipeline/fn-structure-validator/Dockerfile
fns-sidecars/fn-sc-branch/Dockerfile
fns-sidecars/fn-sc-processapi-report/Dockerfile
fns-sidecars/hl7-file-sink/Dockerfile

add the PORT environment variable so that inside the container, the function runs on a higher port than the default of 80

update Dockerfiles to set PORT environment variable

---

fns-hl7-pipeline/fn-lake-segs-transformer/deployZip.sh

uncomment code, fix rm statement

lake of segments - fix deploy zip
