- CHANGELOG.md
- Added message_info to metadata payload with relevant information from message, including routing.
- Updated mmg-based-transformer with exception handling for bad format event hub messages or transformations exceptions.
- Updated mmg-sql-transformer with exception handling for bad format event hub messages or transformations exceptions.
- Updated mmg-sql-transformer for messsage_profile_identifier changed from tables to flat model.
- Updated all functions for dev for function names based on new teraform config and added sample reports in all functions.
- Upgraded Nist Libraries for scala 2.13 and retrofitted upgrade to our own lib-nist-validator.
- Created first draft of Lab Template MMG configuration.
- Fixed bug where JSON was supressing elements with NULL values in lib-dex-commons.
> Release 0.0.10

- fns-hl7-pipeline/fn-redactor/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
Redactor was not reading message_info.type properly.
> fixing message type retrieval

- fns-hl7-pipeline/fn-mmg-sql-transformer/src/main/resources/DefaultFieldsProfileX.json
I'm proposing these changes to the "preferred components" list for the MMG-in-SQL model to reduce the number of empty/null fields in the tables and provide more meaningful information for SN data type
> remove components that are consistently blank, add SN components

- fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/receiver/Function.kt
- fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/receiver/FunctionConfig.kt
In Receiver-Debatcher: Made BlobIngestContainerName accessible from FunctionConfig and replaced hard-coded reference in Function with variable reference. This makes it possible to actually switch storage containers :)
> Remove hard-coded container name

- local_libs/lib-bumblebee/src/test/groovy/gov/cdc/hl7/bumblebee/TemplateTransformerSpec.groovy
change .size property reference to .size() method call in TemplateTransformerSpec.groovy
> #HL7-2196 Fix OBR size error in Unit test

- .github/workflows/hl7-remote-cicd.yml
correct typo in nist validator CI trigger name
> HL7-2265-correct typo in nist validator CI trigger name

- fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/validation/structure/ValidatorFunction.kt
- fns-hl7-pipeline/fn-structure-validator/src/test/kotlin/gov/cdc/dex/ValidationTest.kt
Updated to spit outcome into a single Event Hub Topic. 
Main change was in the `getEhDestination()` function.
> Hl7 2335 strucvalid elr deprecate

- local_libs/lib-nist-validator/build.gradle.kts
- local_libs/lib-nist-validator/src/test/java/gov/cdc/nist/validator/ProfileManagerTest.java
update kotlin version because version 1.7.20 is broken. Updating the kotlin version fixed the tests. 1.7.20 seems to be broke where is says the version cannot be resolved. All dependencies of 1.7.20 including the testing library will throw errors. This has happened in past versions.
https://youtrack.jetbrains.com/issue/KT-53209
https://youtrack.jetbrains.com/issue/KT-47477/Could-not-resolve-kotlin-test-during-project-import-in-case-of-multiplatform-with-only-JVM-target-platform
> update kotlin version

- fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
- fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
metadata.provenance.source_metadata accommodates dynamic metadata.
null when no dynamic meta present
data absent
> update for dynamic metadata

- fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
- fns-hl7-pipeline/fn-structure-validator/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
Instead of loading all profiles up front, load each one on demand (once) and keep it in a MutableMap for future use
> Structure Validator load profiles on demand #HL7-2495

- svc-hl7-replay/openapi.properties
- svc-hl7-replay/pom.xml
- svc-hl7-replay/src/main/kotlin/gov/cdc/dex/replay/service/Application.kt
- svc-hl7-replay/src/main/kotlin/gov/cdc/dex/replay/service/ReplayController.kt
- svc-hl7-replay/src/main/resources/application.yml
added replay/{file_uuid} replay/{message_uuid} POST including parameters
and APi responses with  different HTTP status codes
Created data class for Request Object for replay with different filtering options
added openapi.properties for Open API definition
updated pom with dependancies for swagger
changed deployment section of the pom file for azure-webapp-maven-plugin
corrected enum type class (MessageQueryType) to correctly detect enumtype for message_query
removed 404 HTTP Status Code and added 403, and 500
removed existing endpoints that are no longer needed
updated description for the Replay API
restructured imported libraries and removed unused ones.
> HL7-2519: Create OpenAPI documentation for the Replay API functionality

- fns-hl7-pipeline/fn-receiver-debatcher/pom.xml
> Receiver-Debatcher update Azure BOM to 1.2.18 to fix eventhub send errors

- fns-hl7-pipeline/fn-redactor/pom.xml
> Redactor update Azure BOM to 1.2.18 to fix eventhub send errors

- fns-hl7-pipeline/fn-structure-validator/pom.xml
> Structure Validator update Azure BOM to 1.2.18 to fix eventhub send errors

- fns-hl7-pipeline/fn-lake-segs-transformer/pom.xml
> Lake of Segments update Azure BOM to 1.2.18 to fix eventhub send errors

- fns-hl7-pipeline/fn-hl7-json-lake/pom.xml
> JSON-Lake update Azure BOM to 1.2.18 to fix eventhub send errors

- svc-hl7-validation/README.md
- svc-hl7-validation/pom.xml
- svc-hl7-validation/src/main/kotlin/gov/cdc/dex/validation/service/ValidationController.kt
update README and swagger docs to include DAART; 
update lib-dex-commons version to 1.0.24-snapshot;
update lib-cloud-proxy version to 0.0.30-snapshot; 
update micronaut-management version to 3.8.7;
bump version to 0.0.37-snapshot
> #HL7-2773 Update Validator documentation to include DAART

- local_libs/lib-bumblebee/src/main/kotlin/gov/cdc/hl7/bumblebee/HL7JsonTransformer.kt
MSH-1 and 2 are hardcoded. Need to fix the attribute name at the code level.
> fixing msh-1 from file_separator to field_separator

- local_libs/lib-dex-commons/build.gradle.kts
upgrade azure-messaging-eventhubs library version to match latest azure bom
> lib-dex-commons: upgrade azure-messaging-eventhubs library version

- fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
- fns-hl7-pipeline/fn-lake-segs-transformer/src/main/kotlin/gov/cdc/dex/hl7/LakeSegsTransProcessMetadata.kt
update process metadata to use 'output' node instead of 'report' node for transformed data
> #HL7-2845 Update lake of segments 'report' to 'output'

- fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
- fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/FunctionConfig.kt
- fns-hl7-pipeline/fn-hl7-json-lake/src/main/kotlin/gov/cdc/dex/hl7/HL7JSONLakeProcessMetadata.kt
update json-lake process metadata to save transformed data to 'output' node instead of 'report' node
> #HL7-2844 Update json-lake 'report' to 'output'

- fns-hl7-pipeline/fn-receiver-debatcher/src/main/kotlin/gov/cdc/dex/hl7/Function.kt
handle return value of List<Int> coming from DedicatedEventHubSender.send
> Receiver-Debatcher: Report on messages that are too large for EventHub

- CHANGELOG.md
- Setting batchCheckpointFrequency to 1 on all Pipeline functions
- Refactored all functions to reuse azure resource connections - event hub, service bus, cosmos db, storage account, etc.
- Added health check to all functions and sidecar functions and configured Health Checks on DEV
- Removed transformation Jsons from Processing status report (hl7-json and lake of segments)
- HL7-Json now no longer serialize attributes with no values
- Replaced processes array on metadata for a single Stage attribute (remove duplication of information on payloads)
- Refactored Receiver debatcher to be called from EventGrid events to avoid the Event hub duplication (Receiver cannot afford to receive duplicate events, otherwise the data will be fully duplicated across the pipeline with a new message_uuid.
- …
> change log 39

- fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/Function.kt
- fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/FunctionConfig.kt
Add configuration environment variables for retry attempts, delay seconds, and timeout
> File-sink sidecar: make retry timeout, attempts, delay time configurable

- local_libs/lib-dex-commons/src/main/kotlin/gov/cdc/dex/azure/health/DependencyChecker.kt
limit retries to 1 and set a smaller timeout than default on event hub health check
> #HL7-2877 lib-dex-commons add timeout to event hub health check

- fns-sidecars/hl7-file-sink/deployZip.sh
- fns-sidecars/hl7-file-sink/pom.xml
- fns-sidecars/hl7-file-sink/src/main/kotlin/gov/cdc/dataexchange/HealthCheckFunction.kt
add event hub and storage account checks to health check, 
remove versions from azure-messaging and azure-eventhubs in pom to force use of BOM version
> #HL7-3074 Enhance File-Sink Sidecar health checks

- fns-hl7-pipeline/fn-hl7-json-lake/src/main/resources/PhinGuideProfile_v2.json
A couple of elements had "place" instead of "placer"
> Json-Lake: fix typos in PhinGuideProfile_v2
